/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.KichThuoc;
import java.util.Date;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import logic.RandomStringGenerator;
import lombok.Builder;
import repository.KichThuocRepo;

/**
 *
 * @author ASUS
 */
public class ViewKichThuoc extends javax.swing.JFrame {

    private KichThuocRepo repo = new KichThuocRepo();
    private DefaultTableModel dtm = new DefaultTableModel();
    private String ma_kich_thuoc;
    private Float kich_thuoc;
    private MenuSanPham sp;

    /**
     * Creates new form ViewKichThuoc
     */
    public ViewKichThuoc() {
        initComponents();
        showDataTable(repo.getAll());
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(ViewKichThuoc.DISPOSE_ON_CLOSE);

        txt_MaKT.disable();
        sp = new MenuSanPham();

    }

    private void showDataTable(List<KichThuoc> lists) {
        dtm = (DefaultTableModel) tbl_KichThuoc.getModel();
        dtm.setRowCount(0);
        AtomicInteger index = new AtomicInteger(1);
        lists.forEach(s -> dtm.addRow(new Object[]{
            index.getAndIncrement(), s.getMa_kich_thuoc(), s.getKich_thuoc(), s.getTrang_thai() == 1 ? "Đang kinh doanh" : "Ngưng kinh doanh"
        }));
    }

    public void detail(int index) {
        KichThuoc kt = repo.getAll().get(index);
        txt_MaKT.setText(kt.getMa_kich_thuoc());
        txt_KT.setText(kt.getKich_thuoc().toString());
        if (kt.getTrang_thai() == 0) {
            rdo_NHD.setSelected(true);
        } else {
            rdo_DHD.setSelected(true);
        }
    }

    public KichThuoc getDataToForm() {
        KichThuoc kt = new KichThuoc();
        kt.setMa_kich_thuoc(ma_kich_thuoc);
        kt.setKich_thuoc(Float.valueOf(txt_KT.getText()));
        kt.setTrang_thai(rdo_DHD.isSelected() ? 1 : 0);
        return kt;
    }

    private Boolean kiemTra_KT() {
        if (txt_KT.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập vào kích thước");
            txt_KT.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaKT = new javax.swing.JTextField();
        txt_KT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KichThuoc = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdo_DHD = new javax.swing.JRadioButton();
        rdo_NHD = new javax.swing.JRadioButton();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã Kích Thước:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kích Thước:");

        txt_MaKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaKTActionPerformed(evt);
            }
        });

        tbl_KichThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã Kích Thước", "Kích Thước", "Trạng Thái"
            }
        ));
        tbl_KichThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KichThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_KichThuoc);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Trạng Thái:");

        buttonGroup1.add(rdo_DHD);
        rdo_DHD.setSelected(true);
        rdo_DHD.setText("Đang kinh doanh");
        rdo_DHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_DHDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_NHD);
        rdo_NHD.setText("Ngưng kinh doanh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdo_DHD)
                .addGap(18, 18, 18)
                .addComponent(rdo_NHD, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdo_DHD)
                    .addComponent(rdo_NHD))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_LamMoi.setText("Làm Mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_Exit)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(42, 42, 42))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)
                                    .addGap(26, 26, 26)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_LamMoi))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_KT, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_MaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_Them)
                        .addGap(11, 11, 11)
                        .addComponent(btn_Sua)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Xoa)
                        .addGap(18, 18, 18)
                        .addComponent(btn_LamMoi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_MaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_KT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Exit)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_DHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_DHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_DHDActionPerformed

    private void tbl_KichThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KichThuocMouseClicked
        // TODO add your handling code here:
        int index = tbl_KichThuoc.getSelectedRow();
        detail(index);
    }//GEN-LAST:event_tbl_KichThuocMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
//        int confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm kích thước này chứ?", "Confirm", JOptionPane.YES_NO_OPTION);
//        if (confirm == 0) {
//            if (repo.checkTrung(txt_MaKT.getText())) {
//                JOptionPane.showMessageDialog(this, "Trùng mã");
//            } else {
//                if (kiemTra_KT()) {
//                    ma_kich_thuoc = RandomStringGenerator.generateRandomString("KT");
//                    repo.add(getDataToForm());
//
//                    showDataTable(repo.getAll());
//
//                    JOptionPane.showMessageDialog(this, "Thêm thành công");
//                } else {
//                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
//                }
//            }
//
//        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm kích thước này chứ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            if (repo.checkTrung(txt_MaKT.getText())) {
                JOptionPane.showMessageDialog(this, "Trùng mã");
            } else {
                if (kiemTra_KT()) {
                    ma_kich_thuoc = RandomStringGenerator.generateRandomString("KT");
                    repo.add(getDataToForm());
                    showDataTable(repo.getAll());

                    // Cập nhật ComboBox
                    SwingUtilities.invokeLater(() -> sp.loadCBB_KT());

                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void txt_MaKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaKTActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        int index = tbl_KichThuoc.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa kích thước này không?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng để xóa");
            } else {
                repo.delete(repo.getAll().get(index).getId());
                showDataTable(repo.getAll());
                JOptionPane.showMessageDialog(this, "Xóa thành cônng!");
            }
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        int index = tbl_KichThuoc.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn sửa kích thước này chứ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng để sửa");
            } else {
                repo.update(getDataToForm(), repo.getAll().get(index).getId());
                showDataTable(repo.getAll());
                JOptionPane.showMessageDialog(this, "Sửa thành cônng!");

            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed
    public void clear() {
        txt_MaKT.setText("");
        txt_KT.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKichThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKichThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKichThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKichThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKichThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_DHD;
    private javax.swing.JRadioButton rdo_NHD;
    private javax.swing.JTable tbl_KichThuoc;
    private javax.swing.JTextField txt_KT;
    private javax.swing.JTextField txt_MaKT;
    // End of variables declaration//GEN-END:variables
}
